#!/bin/sh
#

THIS_VERSION="CONDOR"

check_version () {

    if test x"$QSUB_BASENAME" = "xcondor_submit"; then
	echo "CONDOR"
    fi
}

set_version () {

    QSUB_BASENAME="condor_submit "
    if [ -z "$QCONF" ];then QCONF="UNKNOWN"; fi
    if [ -z "$BL1" ];then BL1=""; fi
    if [ -z "$BL2" ];then BL2=""; fi
    if [ -z "$BL3" ];then BL3=""; fi
    if [ -z "$BL4" ];then BL4=""; fi
    if [ -z "$BL5" ];then BL5=""; fi
    if [ -z "$BL6" ];then BL6=""; fi

}


get_properties () {
    NODEFILE="NONE"
}

patch_submission () {
    JSUB="$QSUB"
}

find_queue () {
    DUMMY=""
}
