#!/bin/sh
#

THIS_VERSION="HP_JMS"

check_version () {

    if test x"$QSUB_BASENAME" = "job_submit"; then
	echo "HP_JMS"
    fi
}

set_version () {

    QSUB_BASENAME="job_submit"
    if [ -z "$QCONF" ];then QCONF="UNKNOWN"; fi
    if [ -z "$BL1" ];then BL1=""; fi
    if [ -z "$BL2" ];then BL2=""; fi
    if [ -z "$BL3" ];then BL3=""; fi
    if [ -z "$BL4" ];then BL4=""; fi
    if [ -z "$BL5" ];then BL5=""; fi
    if [ -z "$BL6" ];then BL6=""; fi

}

get_properties () {
    NODEFILE="NONE"
}


patch_submission () {

    hour=`echo $wtime | cut -d':' -f1`
    minute=`echo $wtime | cut -d':' -f2`
    ttime=`echo $hour * 60 + $minute | bc`
    ctime=`expr $ttime / $np`
    ctime=`expr $ctime \* 2`
    JSUB="$QSUB -t $ctime -T $ttime -m $memory -c $QUEUE -p $np"

}


find_queue () {

    generic_qname="parallel multi mpi mpp mpich lam para par batch default"
    QUEUE="p"

}

