#!/bin/sh
#

THIS_VERSION="LOAD_LEVELER"

check_version () {

    if test x"$QSUB_BASENAME" = "xllsubmit"; then
	echo "LOAD_LEVELER"
    fi
}

set_version () {

    QSUB_BASENAME="llsubmit"
    if [ -z "$QCONF" ];then QCONF="UNKNOWN"; fi
    if [ -z "$BL1" ];then BL1=""; fi
    if [ -z "$BL2" ];then BL2=""; fi
    if [ -z "$BL3" ];then BL3=""; fi
    if [ -z "$BL4" ];then BL4=""; fi
    if [ -z "$BL5" ];then BL5=""; fi
    if [ -z "$BL6" ];then BL6=""; fi

}


get_properties () {
    NODEFILE="$LOADL_PROCESSOR_LIST"
}


patch_submission () {
    JSUB="$QSUB"
}

find_queue () {
    DUMMY=""
}
